# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: specfiles/restraint-upstream.spec

# add or remove files that should be synced
synced_files:
  - src: restraint-upstream.spec
    dest: restraint.spec

upstream_package_name: restraint
# downstream (Fedora) RPM package name
downstream_package_name: restraint

# Valid metadata targets can be check by command
# copr list-chroots
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - centos-stream-8-aarch64
      - centos-stream-8-x86_64
      - fedora-36-aarch64
      - fedora-36-armhfp
      - fedora-36-s390x
      - fedora-36-x86_64
      - fedora-37-aarch64
      - fedora-37-armhfp
      - fedora-37-s390x
      - fedora-37-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-armhfp
      - fedora-rawhide-i386
      - fedora-rawhide-x86_64
      - epel-8-aarch64
      - epel-8-x86_64
      - epel-7-x86_64

notifications:
  pull_request:
    successful_build: false
# Restraint is not accepted in Fedora (yet)
#- job: propose_downstream
  #trigger: release
  #metadata:
    #dist-git-branch: fedora-all

