#!/bin/bash

#
# Tell beakerlib what command to use to report results
#
. /usr/share/restraint/plugins/helpers

rstrnt_info "*** Running Plugin: $0"

export BEAKERLIB_COMMAND_REPORT_RESULT=/usr/bin/rstrnt-report-result
export BEAKERLIB_COMMAND_SUBMIT_LOG=/usr/bin/rstrnt-report-log

exec "$@"
