#!/bin/bash

#
# If the following variables aren't defined try and guess them from the system
#

. /usr/share/restraint/plugins/helpers

rstrnt_info "*** Running Plugin: $0"

if [ -z "$RSTRNT_NOPLUGINS" ]; then

    if [ -z "$OUTPUTFILE" ]; then
        export OUTPUTFILE=`mktemp /mnt/testarea/tmp.XXXXXX`
    fi

    if [ -e $OUTPUTFILE ]; then
        if [ -h /mnt/testarea/current.log ]; then
                ln -sf $OUTPUTFILE /mnt/testarea/current.log
        else
                ln -s $OUTPUTFILE /mnt/testarea/current.log
        fi
    fi
fi

if [ -z "$HOSTNAME" ]; then
   HOSTNAME=$(hostname)
fi

if [ -z "$RSTRNT_OSARCH" ]; then
        RSTRNT_OSARCH=$(uname -i)
fi

if [ -z "$RSTRNT_OSMAJOR" ]; then
        RSTRNT_OSMAJOR=$(cat /etc/redhat-release | sed -e 's/\(.*\)release\s\([0-9]*\).*/\1\2/; s/\s//g')
fi

exec "$@"
