#!/bin/bash

. /usr/share/restraint/plugins/helpers

rstrnt_info "*** Running Plugin: $0"

# Don't run from PLUGINS
if [ -z "$RSTRNT_NOPLUGINS" ]; then
    # If we rebooted we need to re-post all the previous events
    if [ -e "/etc/restraint/rstrnt_events" ]; then
        for event in $(cat /etc/restraint/rstrnt_events); do
            rstrnt_info "event $event "$(rstrnt-sync set $event)
        done
    fi
fi
exec "$@"
