#!/bin/sh

. /usr/share/restraint/plugins/helpers

rstrnt_info "*** Running Plugin: $0"

# Don't run from PLUGINS
if [ -z "$RSTRNT_NOPLUGINS" ]; then
    if [ -e "/opt/staf/STAFEnv.sh" ]; then
        . /opt/staf/STAFEnv.sh start
        rstrnt_debug "**** Staf is installed"
        rstrnt_debug "**** Pinging STAFProc"
        rstrnt_debug $(staf local ping ping)
        if [ $? -eq 21 ]; then
            rstrnt_info "**** Starting STAFProc"
            (setsid nohup /opt/staf/bin/STAFProc &) 2>/dev/null
            # If we rebooted we need to re-post all the previous events
            if [ -e "/var/lib/restraint/staf_sem_post_event" ]; then
                for event in $(cat /var/lib/restraint/staf_sem_post_event); do
                    rstrnt_info "event $event "$(staf local sem post event $event)
                done
            fi
        fi
    fi
fi
exec "$@"
