#!/bin/bash

. /etc/os-release

if [ -f "/run/ostree-booted" ]; then
    # OSTree based filesystems are read-only and install with rpm-ostree
    RSTRNT_PKG_CMD=${RSTRNT_PKG_CMD:-rpm-ostree}
    RSTRNT_PKG_ARGS=${RSTRNT_PKG_ARGS:-' '}
    RSTRNT_PKG_INSTALL=${RSTRNT_PKG_INSTALL:-install -y --idempotent --allow-inactive --apply-live}
elif [ 0"$VERSION_ID" -gt 21 ]; then
    # Fedora 22 and newer use dnf as default
    RSTRNT_PKG_CMD=${RSTRNT_PKG_CMD:-dnf}
fi
