#!/bin/bash

# A dummy "implementation" of yum for tests.

# strip out options we don't care about
args=()
for a in "$@"; do
    case "$a" in
        -*|--*) ;;   # ignore options
        *) args+=("$a") ;;
    esac
done

# rebuild positional args
set -- "${args[@]}"

if [[ "$1" == install ]]; then
    shift
    if [[ "$*" == *fail* ]] ; then
        echo "dummy yum: fail" >&2
        # Something is wrong with GIO - without the sleep we sometimes don't get 
        # the last line of data.
        sleep .11
        exit 1
    fi
    echo "dummy yum: installing $*"
    # Something is wrong with GIO - without the sleep we sometimes don't get 
    # the last line of data.
    sleep .11
    exit 0
fi

echo "dummy yum: unrecognised arguments" >&2
exit 1
