#!/bin/sh

PLUGIN=$(basename $0)

SLABLOG=$(mktemp)

function WatchFile ()
{
    FILE=$1

    TMPFILE=$(mktemp -p /mnt/testarea -t Watch.XXXXX)
    while true; do
        diff=$(diff -q $FILE $TMPFILE)
        rc=$?
        if [ $rc != 0 ]; then
            cat $FILE > $TMPFILE
        else
            rm $TMPFILE
            return 0
        fi
        sleep 2
    done
}

function SysRq ()
{
    ACTION=$1
    logger -p local2.info -t "List of $ACTION Tasks" Start
    sleep 1
    echo $ACTION > /proc/sysrq-trigger
    WatchFile /var/log/messages
    logger -p local2.info -t "List of $ACTION Tasks" Stop
}

# Verbose tree view of running processes:

ps -elfH | logger -p local2.info -t "LWD:ps-elfH"

# Get some system information from the system

PROCLIST='m t w'

for p in $PROCLIST ; do
    # Dump a list of blocked tasks and their information
    SysRq $p
    sleep 2
done

# Send slab info to a file for logging
timestamp=$(/bin/date '+%F %T')
echo "Dumping slabinfo - Start - $timestamp" >> $SLABLOG
cat /proc/slabinfo >> $SLABLOG
timestamp=$(/bin/date '+%F %T')
echo "Dumping slabinfo - Stop - $timestamp" >> $SLABLOG
logger -p local2.info -t "SlabCacheInfo" -f $SLABLOG

# Submit dmesg log if any output
rstrnt-report-log -l /var/log/messages

# Upload any logs the user may want
if [ -e $TESTPATH/logs2get ]; then
    for l in `cat $TESTPATH/logs2get`; do
        rstrnt-report-log -l $l
    done
fi

rm -f $SLABLOG
