#!/bin/bash

# If local watchdog triggers we reboot to attempt to get things
# in a sane state again.

PLUGIN=$(basename $0)

rstrnt-report-result --no-plugins $TEST/$PLUGIN WARN 0
rstrnt-abort -t task
rstrnt-reboot
