#!/bin/bash
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

PATH=/sbin:/usr/sbin:$PATH

/usr/bin/rstrnt-prepare-reboot
shutdown -r now

# Wait for the shutdown to kill us..  we don't want control to go back
#  to the test harness.
while (true); do
    sleep 666
done
