#!/bin/sh
PATH=/sbin:/usr/sbin:$PATH

if efibootmgr &>/dev/null ; then
    os_boot_entry=$(efibootmgr | awk '/BootCurrent/ { print $2 }')
    # fall back to /root/EFI_BOOT_ENTRY.TXT if it exists and BootCurrent is not available
    if [[ -z "$os_boot_entry" && -f /root/EFI_BOOT_ENTRY.TXT ]] ; then
        os_boot_entry=$(</root/EFI_BOOT_ENTRY.TXT)
    fi
    if [[ -n "$os_boot_entry" ]] ; then
        logger -s "efibootmgr -n $os_boot_entry"
        efibootmgr -n $os_boot_entry
    else
        logger -s "Could not determine value for BootNext!"
    fi
fi

/sbin/shutdown -r now

# Wait for the shutdown to kill us..  we don't want control to go back
#  to the test harness.
while (true); do
    sleep 666
done
