#ifndef _RESTRAINT_ERRORS_H
#define _RESTRAINT_ERRORS_H

#include <glib.h>

#define RESTRAINT_ERROR (restraint_error_quark ())

typedef enum {
    RESTRAINT_PARSE_ERROR_BAD_SYNTAX, /* parse errors */
    RESTRAINT_MISSING_FILE, /* Missing file*/
    RESTRAINT_OPEN, /* Unable to open file*/
    RESTRAINT_ALREADY_RUNNING_RECIPE_ERROR,
    RESTRAINT_TASK_RUNNER_WATCHDOG_ERROR,
    RESTRAINT_TASK_RUNNER_STDERR_ERROR,
    RESTRAINT_TASK_RUNNER_FORK_ERROR,
    RESTRAINT_TASK_RUNNER_CHDIR_ERROR,
    RESTRAINT_TASK_RUNNER_EXEC_ERROR,
    RESTRAINT_TASK_RUNNER_RC_ERROR,
    RESTRAINT_TASK_RUNNER_RESULT_ERROR,
    RESTRAINT_TASK_RUNNER_FETCH_ERROR,
    RESTRAINT_TASK_RUNNER_RECIPE_ABORTED,
    RESTRAINT_TASK_RUNNER_SCHEMA_ERROR,
    RESTRAINT_TASK_RUNNER_ABORTED,
    RESTRAINT_SSH_ERROR,
    RESTRAINT_CMDLINE_ERROR,
    RESTRAINT_NO_RESTRAINTD_RUNNING_ERROR,
    RESTRAINT_TOO_MANY_RESTRAINTD_RUNNING,
} RestraintError;

GQuark restraint_error_quark (void);

#endif
