#!/bin/bash
#
# restraintd:	Start the restraint Harness server
#
# chkconfig:	2345 98 10
# description:	The restraint Harness server.

# Source function library.
. /etc/rc.d/init.d/functions

prog=restraintd

if [ -f /etc/sysconfig/$prog ]; then
    . /etc/sysconfig/$prog
fi

LOCKFILE=/var/lock/subsys/$prog

start() {
    check_beaker
    echo -n $"Starting $prog: "
    daemon "(( $prog 3>&1 1>&2 2>&3 ) | tee /dev/console ) >> /var/log/restraintd.log 2>&1 &"
    RETVAL=$?
    echo
    if test $RETVAL = 0; then
        touch $LOCKFILE
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    for pid in $(pidof restraintd); do
        kill $pid
    done
    RETVAL=$?
    echo
    rm -f $LOCKFILE
    return $RETVAL
}

restart() {
    stop
    start
}

condrestart(){
	[ -e $LOCKFILE ] && restart
	return 0
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status $prog
	RETVAL=$?
        ;;
    restart)
	restart
	;;
    condrestart|try-restart)
	condrestart
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    usage|*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload|usage}"
	;;
esac
exit $RETVAL
