name: Merge-checks

on:
  push:
    branches:
      - master

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        container: ["fedora:36", "fedora:37"]
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/${{ matrix.container }}

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
        dnf install -y 'dnf-command(builddep)' git-daemon python3-flask python3-requests python3-pytest python3-six procps-ng
    - name: Install restraint deps
      run: |
        dnf builddep --spec specfiles/restraint-upstream.spec -y
    - name: Run tests
      run: |
        set -o pipefail
        make check | tee unittests.out
        mv unittests.out /__w/unittests.out
    - uses: actions/upload-artifact@v1
      with:
        name: unittests.out
        path: /home/runner/work/unittests.out

  valgrind:
    strategy:
      fail-fast: false
      matrix:
        container: ["fedora:36", "fedora:37"]
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/${{ matrix.container }}

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
        dnf install -y 'dnf-command(builddep)' valgrind git-daemon procps-ng
    - name: Install restraint deps
      run: |
        dnf builddep --spec specfiles/restraint-upstream.spec -y
    - name: Run valgrind
      run: |
        set -o pipefail
        make valgrind 2>&1 | tee valgrind.out
        mv valgrind.out /__w/valgrind.out
    - uses: actions/upload-artifact@v1
      with:
        name: valgrind.out
        path: /home/runner/work/valgrind.out

