name: Merge-checks

on:
  push:
    branches:
      - master

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        image: [quay.io/fedora/fedora]
        version: ["40", "41"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        dnf install -y 'dnf-command(builddep)' git-daemon python3-flask python3-requests python3-pytest python3-six procps-ng
    - name: Install restraint deps
      run: |
        dnf builddep --spec specfiles/restraint-upstream.spec -y
    - name: Run tests
      run: |
        set -o pipefail
        make check | tee unittests.out
        mv unittests.out /__w/unittests.out
    - uses: actions/upload-artifact@v4
      with:
        name: unittests-${{ matrix.version }}.out
        path: /home/runner/work/unittests.out

  valgrind:
    strategy:
      fail-fast: false
      matrix:
        image: [quay.io/fedora/fedora]
        version: ["40", "41"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        dnf install -y 'dnf-command(builddep)' valgrind git-daemon procps-ng
    - name: Install restraint deps
      run: |
        dnf builddep --spec specfiles/restraint-upstream.spec -y
    - name: Run valgrind
      run: |
        set -o pipefail
        make valgrind 2>&1 | tee valgrind.out
        mv valgrind.out /__w/valgrind.out
    - uses: actions/upload-artifact@v4
      with:
        name: valgrind-${{ matrix.version }}.out
        path: /home/runner/work/valgrind.out
